# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/Downloads/ParaView/Examples/Plugins/GUIToolBar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/Downloads/ParaView/Examples/Plugins/GUIToolBar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Downloads/ParaView/Examples/Plugins/GUIToolBar/CMakeFiles /home/lucas/Downloads/ParaView/Examples/Plugins/GUIToolBar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Downloads/ParaView/Examples/Plugins/GUIToolBar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GUIMyToolBar

# Build rule for target.
GUIMyToolBar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GUIMyToolBar
.PHONY : GUIMyToolBar

# fast build rule for target.
GUIMyToolBar/fast:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/build
.PHONY : GUIMyToolBar/fast

# target to build an object file
GUIMyToolBar_Plugin.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/GUIMyToolBar_Plugin.o
.PHONY : GUIMyToolBar_Plugin.o

# target to preprocess a source file
GUIMyToolBar_Plugin.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/GUIMyToolBar_Plugin.i
.PHONY : GUIMyToolBar_Plugin.i

# target to generate assembly for a file
GUIMyToolBar_Plugin.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/GUIMyToolBar_Plugin.s
.PHONY : GUIMyToolBar_Plugin.s

# target to build an object file
MyToolBarActions.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/MyToolBarActions.o
.PHONY : MyToolBarActions.o

# target to preprocess a source file
MyToolBarActions.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/MyToolBarActions.i
.PHONY : MyToolBarActions.i

# target to generate assembly for a file
MyToolBarActions.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/MyToolBarActions.s
.PHONY : MyToolBarActions.s

# target to build an object file
MyToolBarActionsImplementation.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/MyToolBarActionsImplementation.o
.PHONY : MyToolBarActionsImplementation.o

# target to preprocess a source file
MyToolBarActionsImplementation.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/MyToolBarActionsImplementation.i
.PHONY : MyToolBarActionsImplementation.i

# target to generate assembly for a file
MyToolBarActionsImplementation.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/MyToolBarActionsImplementation.s
.PHONY : MyToolBarActionsImplementation.s

# target to build an object file
adddialog.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/adddialog.o
.PHONY : adddialog.o

# target to preprocess a source file
adddialog.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/adddialog.i
.PHONY : adddialog.i

# target to generate assembly for a file
adddialog.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/adddialog.s
.PHONY : adddialog.s

# target to build an object file
moc_GUIMyToolBar_Plugin.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_GUIMyToolBar_Plugin.o
.PHONY : moc_GUIMyToolBar_Plugin.o

# target to preprocess a source file
moc_GUIMyToolBar_Plugin.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_GUIMyToolBar_Plugin.i
.PHONY : moc_GUIMyToolBar_Plugin.i

# target to generate assembly for a file
moc_GUIMyToolBar_Plugin.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_GUIMyToolBar_Plugin.s
.PHONY : moc_GUIMyToolBar_Plugin.s

# target to build an object file
moc_MyToolBarActions.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_MyToolBarActions.o
.PHONY : moc_MyToolBarActions.o

# target to preprocess a source file
moc_MyToolBarActions.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_MyToolBarActions.i
.PHONY : moc_MyToolBarActions.i

# target to generate assembly for a file
moc_MyToolBarActions.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_MyToolBarActions.s
.PHONY : moc_MyToolBarActions.s

# target to build an object file
moc_MyToolBarActionsImplementation.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_MyToolBarActionsImplementation.o
.PHONY : moc_MyToolBarActionsImplementation.o

# target to preprocess a source file
moc_MyToolBarActionsImplementation.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_MyToolBarActionsImplementation.i
.PHONY : moc_MyToolBarActionsImplementation.i

# target to generate assembly for a file
moc_MyToolBarActionsImplementation.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_MyToolBarActionsImplementation.s
.PHONY : moc_MyToolBarActionsImplementation.s

# target to build an object file
moc_adddialog.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_adddialog.o
.PHONY : moc_adddialog.o

# target to preprocess a source file
moc_adddialog.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_adddialog.i
.PHONY : moc_adddialog.i

# target to generate assembly for a file
moc_adddialog.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_adddialog.s
.PHONY : moc_adddialog.s

# target to build an object file
moc_modelwidget.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_modelwidget.o
.PHONY : moc_modelwidget.o

# target to preprocess a source file
moc_modelwidget.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_modelwidget.i
.PHONY : moc_modelwidget.i

# target to generate assembly for a file
moc_modelwidget.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_modelwidget.s
.PHONY : moc_modelwidget.s

# target to build an object file
moc_qtuple.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_qtuple.o
.PHONY : moc_qtuple.o

# target to preprocess a source file
moc_qtuple.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_qtuple.i
.PHONY : moc_qtuple.i

# target to generate assembly for a file
moc_qtuple.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_qtuple.s
.PHONY : moc_qtuple.s

# target to build an object file
moc_tablemodel.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_tablemodel.o
.PHONY : moc_tablemodel.o

# target to preprocess a source file
moc_tablemodel.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_tablemodel.i
.PHONY : moc_tablemodel.i

# target to generate assembly for a file
moc_tablemodel.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/moc_tablemodel.s
.PHONY : moc_tablemodel.s

# target to build an object file
modelwidget.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/modelwidget.o
.PHONY : modelwidget.o

# target to preprocess a source file
modelwidget.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/modelwidget.i
.PHONY : modelwidget.i

# target to generate assembly for a file
modelwidget.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/modelwidget.s
.PHONY : modelwidget.s

# target to build an object file
tablemodel.o:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/tablemodel.o
.PHONY : tablemodel.o

# target to preprocess a source file
tablemodel.i:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/tablemodel.i
.PHONY : tablemodel.i

# target to generate assembly for a file
tablemodel.s:
	$(MAKE) -f CMakeFiles/GUIMyToolBar.dir/build.make CMakeFiles/GUIMyToolBar.dir/tablemodel.s
.PHONY : tablemodel.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GUIMyToolBar"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GUIMyToolBar_Plugin.o"
	@echo "... GUIMyToolBar_Plugin.i"
	@echo "... GUIMyToolBar_Plugin.s"
	@echo "... MyToolBarActions.o"
	@echo "... MyToolBarActions.i"
	@echo "... MyToolBarActions.s"
	@echo "... MyToolBarActionsImplementation.o"
	@echo "... MyToolBarActionsImplementation.i"
	@echo "... MyToolBarActionsImplementation.s"
	@echo "... adddialog.o"
	@echo "... adddialog.i"
	@echo "... adddialog.s"
	@echo "... moc_GUIMyToolBar_Plugin.o"
	@echo "... moc_GUIMyToolBar_Plugin.i"
	@echo "... moc_GUIMyToolBar_Plugin.s"
	@echo "... moc_MyToolBarActions.o"
	@echo "... moc_MyToolBarActions.i"
	@echo "... moc_MyToolBarActions.s"
	@echo "... moc_MyToolBarActionsImplementation.o"
	@echo "... moc_MyToolBarActionsImplementation.i"
	@echo "... moc_MyToolBarActionsImplementation.s"
	@echo "... moc_adddialog.o"
	@echo "... moc_adddialog.i"
	@echo "... moc_adddialog.s"
	@echo "... moc_modelwidget.o"
	@echo "... moc_modelwidget.i"
	@echo "... moc_modelwidget.s"
	@echo "... moc_qtuple.o"
	@echo "... moc_qtuple.i"
	@echo "... moc_qtuple.s"
	@echo "... moc_tablemodel.o"
	@echo "... moc_tablemodel.i"
	@echo "... moc_tablemodel.s"
	@echo "... modelwidget.o"
	@echo "... modelwidget.i"
	@echo "... modelwidget.s"
	@echo "... tablemodel.o"
	@echo "... tablemodel.i"
	@echo "... tablemodel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

